// DOM element references
const sourceInput = document.getElementById('sourceCity');
const destinationInput = document.getElementById('destinationCity');
const sourceAutocomplete = document.getElementById('sourceAutocomplete');
const destinationAutocomplete = document.getElementById('destinationAutocomplete');
const transportModeInput = document.getElementById('transportMode');
const transportAutocomplete = document.getElementById('transportAutocomplete');
const calculateButton = document.getElementById('calculateButton');
const calculatorForm = document.getElementById('calculatorForm');
const resultsSection = document.getElementById('results');
